CREATE DATABASE db_tienda
GO
USE db_tienda
GO

CREATE TABLE Tipos(
	[Id] INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	[Nombre] NVARCHAR(50) NOT NULL,
);

CREATE TABLE Personas(
	[Id] INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	[Cedula] NVARCHAR(50) NOT NULL,
	[Nombre] NVARCHAR(50) NOT NULL,
	[Tipo] INT REFERENCES Tipos([Id]),
	[Imagen] NVARCHAR(MAX) NULL,
	[Fecha] DATE DEFAULT GETDATE(),
	[Activo] BIT
);

